-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.rol
(
    id_rol integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nombre_rol character varying(50) NOT NULL,
    descripcion text NOT NULL,
    PRIMARY KEY (id_rol),
    CONSTRAINT "nom_rol_UQ" UNIQUE (nombre_rol)
);

CREATE TABLE IF NOT EXISTS public.comerciante
(
    id_comerciante integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    ruc character varying(11) NOT NULL,
    nombre_comcercial character varying(150) NOT NULL,
    razon_social character varying(150) NOT NULL,
    telefono character varying(9) NOT NULL,
    fecha_registro timestamp without time zone DEFAULT now(),
    PRIMARY KEY (id_comerciante),
    CONSTRAINT telefono_uq UNIQUE (telefono),
    CONSTRAINT razon_uq UNIQUE (razon_social)
);

CREATE TABLE IF NOT EXISTS public.configuracion
(
    id_configuracion integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    moneda character varying(3) NOT NULL DEFAULT 'PEN',
    igv_porcentaje numeric(4, 2) NOT NULL,
    comerciante_id_comerciante integer,
    PRIMARY KEY (id_configuracion),
    UNIQUE (comerciante_id_comerciante)
);

CREATE TABLE IF NOT EXISTS public.empleado
(
    id_empleado integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    dni character varying(8) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    correo character varying(100) NOT NULL,
    clave character varying(255) NOT NULL,
    estado boolean NOT NULL,
    rol_id_rol integer NOT NULL,
    sucursal_id_sucursal integer NOT NULL,
    PRIMARY KEY (id_empleado),
    CONSTRAINT dni_uq UNIQUE (dni),
    CONSTRAINT correo_uq UNIQUE (correo)
);

CREATE TABLE IF NOT EXISTS public.sucursal
(
    id_sucursal integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    nombre_sucursal character varying(100) NOT NULL,
    direccion character varying(250) NOT NULL,
    comerciante_id_comerciante integer NOT NULL,
    PRIMARY KEY (id_sucursal),
    CONSTRAINT nom_sucursal_uq UNIQUE (nombre_sucursal)
);

CREATE TABLE IF NOT EXISTS public.suscripcion
(
    id_suscripcion integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    tipo_plan character varying(50) NOT NULL,
    fecha_inicio date NOT NULL DEFAULT now(),
    fecha_fin date NOT NULL,
    estado_pago character varying(20) NOT NULL,
    comerciante_id_comerciante integer,
    PRIMARY KEY (id_suscripcion)
);

CREATE TABLE IF NOT EXISTS public.historial_login
(
    id_log integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    fecha_hora timestamp without time zone NOT NULL DEFAULT now(),
    dispositivo character varying(150) NOT NULL,
    empleado_id_empleado integer NOT NULL,
    PRIMARY KEY (id_log)
);

ALTER TABLE IF EXISTS public.configuracion
    ADD FOREIGN KEY (comerciante_id_comerciante)
    REFERENCES public.comerciante (id_comerciante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleado
    ADD FOREIGN KEY (rol_id_rol)
    REFERENCES public.rol (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleado
    ADD FOREIGN KEY (sucursal_id_sucursal)
    REFERENCES public.sucursal (id_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sucursal
    ADD FOREIGN KEY (comerciante_id_comerciante)
    REFERENCES public.comerciante (id_comerciante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.suscripcion
    ADD FOREIGN KEY (comerciante_id_comerciante)
    REFERENCES public.comerciante (id_comerciante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.historial_login
    ADD FOREIGN KEY (empleado_id_empleado)
    REFERENCES public.empleado (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;